version: "3.3"
services:
    server:
        build: ./eureka_server
        ports: 
          - "8761:8761"
        image: "eureka-server"
    Zuul:
        build: ./zuul-server
        ports:
        - "8762:8762"
        image: "zuul"
        environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://server:8761/eureka/

        depends_on:
        - server
    user:
        build: ./user-service
        ports:
        - "8085:8085"
        image: "user-service"
        depends_on:
        - server
    order:
        build: ./order-service
        ports:
        - "8082:8082"
        image: "order-service"
        depends_on:
        - server
        - db
    productcatalog:
        build: ./product_catalog_service
        ports:
        - "8083:8083"
        image: "product-catalog-service"
        depends_on:
        - server
        - db
    productrecommendation:
        build: ./product-recommendation-service
        ports:
        - "8084:8084"
        image: "product-recommendation-service"
        depends_on:
        - server
        - dbPostgres
    marketplace:
        build: ./marketplace-service
        ports:
        - "8081:8081"
        image: "marketplace-service"
        depends_on:
        - server
        - db
        
    mongodb:
       image: mongo:5.0.2
       restart: unless-stopped
       env_file: ./.env
       environment:
       - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
       - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
       ports:
       - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
       volumes:
       - db1:/data/db
    app:
     depends_on:
      - mongodb
     build: ./node-microservice
     restart: unless-stopped
     env_file: ./.env
     ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
     environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
     stdin_open: true
     tty: true

    db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: 'db'
          MYSQL_ROOT_PASSWORD: '123'
        ports:
        - '3307:3307'
        expose:
        - '3307'
        volumes:
        - my-db:/var/lib/mysql
    dbPostgres:
        image: postgres:14.1-alpine
        restart: always
        environment:
        - POSTGRES_DB=productrecommendation
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - '5432:5432'
        volumes: 
        - my-db:/var/lib/postgresql/datadb
volumes:
    my-db:
    db1: